name: Format Code
on: [push]

jobs:
  format:
    runs-on: nix
    permissions:
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Run Formatter
        run: nix run .#format --accept-flake-config --extra-experimental-features flakes,nix-command

      - name: Commit Changes
        uses: https://github.com/stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: format code"
