#!/usr/bin/env bash
# Utility script for nix management.

case "$1" in
clean)
	nix-collect-garbage -d
	;;
optimize)
	nix store optimise
	;;
update)
	nix flake update --flake ~/.dotfiles
	;;
edit)
	code ~/.dotfiles
	;;
pull)
	cd ~/.dotfiles
	git pull
	;;
hash)
	nix hash convert --hash-algo sha256 "$(nix-prefetch-url "$2")"
	;;
"")
	home-manager switch --flake ~/.dotfiles#$HOSTNAME -b backup
	;;
*)
	echo "Usage: nx [clean|update|edit|pull|hash|optimize]"
	;;
esac
