#!/usr/bin/env bash
# Utility script for nix management.

case "$1" in
clean)
	nix-collect-garbage -d
	;;
update)
	nix flake update --flake ~/.dotfiles
	;;
edit)
	code ~/.dotfiles
	;;
pull)
	cd ~/.dotfiles
	git pull
	;;
"")
	home-manager switch --flake ~/.dotfiles#$HOSTNAME
	;;
*)
	echo "Usage: nx [clean|update|edit|pull]"
	;;
esac
