name: "Build All NixOS Systems"
on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-systems:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: # list of hostnames to cache for
        hostname: [ehrman, flynn, huell, hyzenberg, pete]
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30

      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: xelacodes
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          signingKey: "${{ secrets.CACHIX_SECRET_KEY }}"
          # we have to ignore big ticket packages like 1password
          pushFilter: "(-source$|\\.tar\\.gz$|\\.snap$|\\.msi$|1password-8|vscode|plexamp|plex-desktop|joplin-desktop|mongodb-compass|geekbench|headplane-pnpm-deps)"

      - name: Build System
        run: |
          nix build .#nixosConfigurations.${{ matrix.hostname }}.config.system.build.toplevel\
            --option accept-flake-config true
