name: "Build All NixOS Systems"
on:
  push:
    branches:
      - master
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-systems:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: # list of hostnames to cache for
        hostname: [ehrman, flynn, huell, hyzenberg, pete]
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v30

      - name: Setup Cachix
        uses: cachix/cachix-action@v15
        with:
          name: xelacodes
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"
          signingKey: "${{ secrets.CACHIX_SECRET_KEY }}"
          # we have to ignore big ticket packages like 1password
          pushFilter: "(-source$|\\.tar\\.gz$|\\.snap$|\\.msi$|\\.iso$|\\.zip$|1password-8|vscode|plexamp|plex-desktop|joplin-desktop|mongodb-compass|geekbench|headplane-pnpm-deps)"

      - name: Build System
        run: |
          nix build .#nixosConfigurations.${{ matrix.hostname }}.config.system.build.toplevel\
            --option accept-flake-config true

      - name: Calculate and Log System Size
        run: |
          SYS_PATH=$(nix build .#nixosConfigurations.${{ matrix.hostname }}.config.system.build.toplevel --no-link --print-out-paths)

          # -s gets the individual path size, -S gets the full recursive closure size
          LOCAL_SIZE=$(nix path-info -sh "$SYS_PATH" | awk '{print $2}')
          CLOSURE_SIZE=$(nix path-info -Sh "$SYS_PATH" | awk '{print $2}')

          echo "=================================================="
          echo "Host: ${{ matrix.hostname }}"
          echo "System Top-Level Path Size: $LOCAL_SIZE"
          echo "Total Runtime Closure Size: $CLOSURE_SIZE"
          echo "=================================================="

          echo "### Size Metrics for \`${{ matrix.hostname }}\`" >> $GITHUB_STEP_SUMMARY
          echo "| Metric | Size |" >> $GITHUB_STEP_SUMMARY
          echo "| :--- | :--- |" >> $GITHUB_STEP_SUMMARY
          echo "| **Top-Level Symlink Tree** | $LOCAL_SIZE |" >> $GITHUB_STEP_SUMMARY
          echo "| **Total Runtime Closure (Disk Space Needed)** | \`$CLOSURE_SIZE\` |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
